grafana:
  adminPassword: change-me-grafana-admin-password
  grafana.ini:
    server:
      root_url: http://k14c102.p.ssafy.io/grafana
      serve_from_sub_path: true
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - k14c102.p.ssafy.io
    path: /grafana
    pathType: Prefix

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - k14c102.p.ssafy.io
    paths:
      - /prometheus
  prometheusSpec:
    externalUrl: http://k14c102.p.ssafy.io/prometheus
    routePrefix: /prometheus
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - k14c102.p.ssafy.io
    paths:
      - /alertmanager
  alertmanagerSpec:
    externalUrl: http://k14c102.p.ssafy.io/alertmanager
    routePrefix: /alertmanager

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
