apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: smartcane
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: smartcane/backend
        property: postgresUser
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: smartcane/backend
        property: postgresPassword
    - secretKey: MYSQL_USER
      remoteRef:
        key: smartcane/backend
        property: mysqlUser
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: smartcane/backend
        property: mysqlPassword
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: smartcane/backend
        property: redisPassword
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: smartcane/backend
        property: awsAccessKeyId
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: smartcane/backend
        property: awsSecretAccessKey
    - secretKey: JWT_SECRET
      remoteRef:
        key: smartcane/backend
        property: jwtSecret
