provider: aws
policy: sync
registry: txt
txtOwnerId: smartcane-k3s
interval: 1m

serviceAccount:
  create: true
  name: external-dns

domainFilters:
  - smartcane.com

sources:
  - ingress

env:
  - name: AWS_DEFAULT_REGION
    value: ap-northeast-2
