apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartcane-backend
  namespace: argocd
spec:
  project: smartcane
  source:
    repoURL: https://lab.ssafy.com/s14-final/S14P31C102.git
    targetRevision: develop
    path: infra/k3s/apps/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: smartcane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
