apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: smartcane
data:
  SPRING_PROFILES_ACTIVE: prod
  POSTGRES_HOST: rds-postgres-stg.ssafyapp.com
  POSTGRES_PORT: "5432"
  POSTGRES_DB: change-me
  MYSQL_HOST: rds-stg.ssafyapp.com
  MYSQL_PORT: "3306"
  MYSQL_DB: change-me
  REDIS_HOST: redis-stg.ssafyapp.com
  REDIS_PORT: "6379"
  AWS_REGION: ap-northeast-2
  S3_BUCKET: ssafyapp-stg-project-prv-data
  S3_PREFIX: 7rat8/
