apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: smartcane
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: smartcane-backend-strip-prefix@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.smartcane.com
      secretName: backend-api-tls
  rules:
    - host: api.smartcane.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
