apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: smartcane
type: Opaque
stringData:
  # PostgreSQL RDS
  POSTGRES_USER: change-me
  POSTGRES_PASSWORD: change-me

  # MySQL RDS
  MYSQL_USER: change-me
  MYSQL_PASSWORD: change-me

  # Redis ElastiCache
  REDIS_PASSWORD: change-me

  # AWS / S3
  AWS_ACCESS_KEY_ID: change-me
  AWS_SECRET_ACCESS_KEY: change-me

  # Application security
  JWT_SECRET: change-me
