apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: smartcane
type: Opaque
stringData:
  # PostgreSQL RDS
  POSTGRES_USER:
  POSTGRES_PASSWORD:

  # MySQL RDS
  MYSQL_USER:
  MYSQL_PASSWORD:

  # Redis ElastiCache
  REDIS_PASSWORD:

  # AWS / S3
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

  # Application security
  JWT_SECRET:
